### ISSUE TITLE
bash train_ppo_en.sh error

### ISSUE THREAD

**Issue by robotzheng** [OpenLMLab/MOSS-RLHF#46]
2024-02-01 15:13:58 - Rank: 4 - INFO - Loading critic model from: models/moss-rlhf-reward-model-7B-en/recover...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 3/3 [01:02<00:00, 20.78s/it]
2024-02-01 15:15:36 - Rank: 5 - INFO - Loading reference model from: models/moss-rlhf-sft-model-7B-en/recover...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 3/3 [01:04<00:00, 21.53s/it]
2024-02-01 15:15:36 - Rank: 2 - INFO - Loading reference model from: models/moss-rlhf-sft-model-7B-en/recover...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 3/3 [01:03<00:00, 21.05s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 3/3 [01:04<00:00, 21.48s/it]
2024-02-01 15:15:36 - Rank: 1 - INFO - Loading reference model from: models/moss-rlhf-sft-model-7B-en/recover...
2024-02-01 15:15:36 - Rank: 3 - INFO - Loading reference model from: models/moss-rlhf-sft-model-7B-en/recover...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 3/3 [01:02<00:00, 20.91s/it]
2024-02-01 15:15:36 - Rank: 6 - INFO - Loading reference model from: models/moss-rlhf-sft-model-7B-en/recover...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 3/3 [01:00<00:00, 20.11s/it]
2024-02-01 15:15:36 - Rank: 4 - INFO - Loading reference model from: models/moss-rlhf-sft-model-7B-en/recover...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 3/3 [01:01<00:00, 20.57s/it]
2024-02-01 15:15:36 - Rank: 0 - INFO - Loading reference model from: models/moss-rlhf-sft-model-7B-en/recover...
2024-02-01 15:17:18 - Rank: 4 - INFO - Loading reward model from: models/moss-rlhf-reward-model-7B-en/recover...
2024-02-01 15:17:18 - Rank: 6 - INFO - Loading reward model from: models/moss-rlhf-reward-model-7B-en/recover...
2024-02-01 15:17:20 - Rank: 1 - INFO - Loading reward model from: models/moss-rlhf-reward-model-7B-en/recover...
2024-02-01 15:17:21 - Rank: 0 - INFO - Loading reward model from: models/moss-rlhf-reward-model-7B-en/recover...
2024-02-01 15:17:21 - Rank: 3 - INFO - Loading reward model from: models/moss-rlhf-reward-model-7B-en/recover...
2024-02-01 15:17:21 - Rank: 2 - INFO - Loading reward model from: models/moss-rlhf-reward-model-7B-en/recover...
2024-02-01 15:17:22 - Rank: 5 - INFO - Loading reward model from: models/moss-rlhf-reward-model-7B-en/recover...
Loading checkpoint shards:  33%|███████████████████████                                              | 1/3 [00:32<01:05, 32.70s/it][2024-02-01 15:18:35,714] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 583055 closing signal SIGTERM
[2024-02-01 15:18:35,715] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 583057 closing signal SIGTERM
[2024-02-01 15:18:35,716] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 583058 closing signal SIGTERM
[2024-02-01 15:18:35,716] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 583059 closing signal SIGTERM
[2024-02-01 15:18:35,717] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 583067 closing signal SIGTERM
[2024-02-01 15:18:48,232] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 1 (pid: 583056) of binary: /opt/conda/envs/safe-rlhf/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/safe-rlhf/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/safe-rlhf/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/opt/conda/envs/safe-rlhf/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1002, in launch_command
    deepspeed_launcher(args)
  File "/opt/conda/envs/safe-rlhf/lib/python3.9/site-packages/accelerate/commands/launch.py", line 718, in deepspeed_launcher
    distrib_run.run(args)
  File "/opt/conda/envs/safe-rlhf/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/envs/safe-rlhf/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))

**Comment by robotzheng** [comment]
File "/opt/conda/envs/safe-rlhf/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=======================================================
train_ppo.py FAILED
-------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-01_15:18:35
  host      : task-20240105100221-21140
  rank      : 6 (local_rank: 6)
  exitcode  : -9 (pid: 583068)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 583068
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-01_15:18:35
  host      : task-20240105100221-21140
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 583056)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 583056

**Comment by robotzheng** [comment]
total        used        free      shared  buff/cache   available
Mem:     1056285128    45529120   836243424     4201328   174512584   976171764
Swap:             0           0           0

**Comment by robotzheng** [comment]
800G RAM 够不够？

**Comment by robotzheng** [comment]
RAM不够，调整了参数跑起来了
